version: '3.6'
services:
  db:
    image: postgres
    #hostname: postgres
    container_name: store-docker-db
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: store
    ports:
      #- 5433:5432
      - target: 5432
        published: 5433
        protocol: tcp
        mode: host
    networks:
      - backdb
    expose:
      - 5433

  back:
    build:
      context: ./back
      target: finalApp
    image: store/back
    container_name: backend
    depends_on:
      - db
    networks:
      - backdb

networks:
  backdb:
    driver: bridge